name: CMake

on:
  pull_request:
    types: [opened, synchronize]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: 'build (os: ${{ matrix.os }})'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}
      - name: Compress build artifact
        run: tar -zcvf ${{ github.workspace }}/build/minigit.tar.gz -C ${{ github.workspace }}/build/bin/${{ env.BUILD_TYPE }} .
      - name: Get short commit hash
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: minigit-${{ matrix.os }}-${{ env.BUILD_TYPE }}-${{ steps.vars.outputs.sha_short }}
          path: ${{ github.workspace }}/build/minigit.tar.gz
