name: CMake

on:
  pull_request:
    types: [opened, synchronize]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    name: 'build (os: ${{ matrix.os }})'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      BUILD_DIR: ${{ github.workspace }}/build
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup and cache vcpkg
        uses: lukka/run-vcpkg@v6
        with:
          setupOnly: true
          vcpkgDirectory: ${{ github.workspace }}/vcpkg
          appendedCacheKey: ${{ hashFiles('**/vcpkg.json') }}
          additionalCachedPaths: ${{ env.BUILD_DIR }}/vcpkg_installed
      - name: Configure CMake
        run: cmake -B ${{ env.BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
      - name: Build
        run: cmake --build ${{ env.BUILD_DIR }} --config ${{ env.BUILD_TYPE }}
      - name: Compress build artifact
        run: tar -zcvf ${{ env.BUILD_DIR }}/minigit.tar.gz -C ${{ env.BUILD_DIR }}/bin/${{ env.BUILD_TYPE }} .
      - name: Get short commit hash
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: minigit-${{ matrix.os }}-${{ env.BUILD_TYPE }}-${{ steps.vars.outputs.sha_short }}
          path: ${{ env.BUILD_DIR }}/minigit.tar.gz
